class_name RiotDiskCleaner
extends RefCounted

## Utility for scanning and safely removing accumulated log files and crash dumps
## generated by the Riot Client and League of Legends across Windows %LOCALAPPDATA%
## and game installation directories.
##
## Safety Guarantees:
## - Only targets designated Logs/ and Crashes/ directories.
## - NEVER touches credential/session files (Sessions, RiotGamesPrivateSettings.yaml,
##   RiotClientSettings.yaml, client.config.yaml), game configs, or profiles.
## - In-use/locked files are safely caught and skipped without aborting the cleanup.

const LOCAL_APPDATA_RIOT := "Riot Games"

## Returns all candidate directory paths that store Riot/League logs and crash dumps.
static func get_cleanable_paths(riot_client_location: String = "") -> Array[String]:
	var paths: Array[String] = []
	var local_appdata := OS.get_environment("LOCALAPPDATA")
	if not local_appdata.is_empty():
		local_appdata = local_appdata.replace("\\", "/")
		var riot_local := local_appdata.path_join(LOCAL_APPDATA_RIOT)
		if DirAccess.dir_exists_absolute(riot_local):
			# 1. Riot Client logs and crashes
			paths.append(riot_local.path_join("Riot Client/Logs"))
			paths.append(riot_local.path_join("Riot Client/Crashes"))

			# 2. League of Legends local appdata logs and crashes
			paths.append(riot_local.path_join("League of Legends/Logs"))
			paths.append(riot_local.path_join("League of Legends/Crashes"))

			# 3. Installer logs (e.g. "Install League of Legends br/Logs")
			var dir := DirAccess.open(riot_local)
			if dir:
				dir.list_dir_begin()
				var entry := dir.get_next()
				while not entry.is_empty():
					if dir.current_is_dir() and entry.begins_with("Install League of Legends"):
						paths.append(riot_local.path_join(entry).path_join("Logs"))
					entry = dir.get_next()
				dir.list_dir_end()

	# 4. League of Legends installation directory Logs
	var league_dir := LeagueSettingsSync.find_league_dir(riot_client_location)
	if not league_dir.is_empty():
		league_dir = league_dir.replace("\\", "/")
		paths.append(league_dir.path_join("Logs"))

	# 5. Sibling / Install dir Logs of Riot Client if existing
	var rc_loc := riot_client_location
	if rc_loc.is_empty():
		var cfg = JsonFile.load_data(AppPaths.CONFIG_FILE)
		if cfg is Dictionary:
			rc_loc = String(cfg.get("RiotClientLocation", ""))
	if not rc_loc.is_empty():
		var rc_base := rc_loc.replace("\\", "/").get_base_dir()
		var rc_logs := rc_base.path_join("Logs")
		if DirAccess.dir_exists_absolute(rc_logs) and not paths.has(rc_logs):
			paths.append(rc_logs)

	# Deduplicate and filter to existing directories
	var valid_paths: Array[String] = []
	for p: String in paths:
		var normalized := p.replace("\\", "/").rstrip("/")
		if not valid_paths.has(normalized) and DirAccess.dir_exists_absolute(normalized):
			valid_paths.append(normalized)

	return valid_paths


## Scans all cleanable paths and sums the total byte size and file count.
## Safe to run on a worker thread.
static func calculate_cleanable_size(riot_client_location: String = "") -> Dictionary:
	var total_bytes: int = 0
	var file_count: int = 0
	var targets := get_cleanable_paths(riot_client_location)

	for target_dir: String in targets:
		var stat := _measure_dir_recursive(target_dir)
		total_bytes += int(stat.get("bytes", 0))
		file_count += int(stat.get("files", 0))

	return {
		"total_bytes": total_bytes,
		"file_count": file_count,
		"targets_count": targets.size(),
	}


## Deletes all log files and crash dumps in the target directories.
## Recursively cleans nested subdirectories (e.g. GameCrashes, GameLogs).
## Returns summary of freed bytes, deleted files, and skipped (locked) files.
## Safe to run on a worker thread.
static func clean_logs(riot_client_location: String = "") -> Dictionary:
	var freed_bytes: int = 0
	var deleted_files: int = 0
	var skipped_files: int = 0
	var targets := get_cleanable_paths(riot_client_location)

	for target_dir: String in targets:
		var res := _delete_dir_contents_recursive(target_dir)
		freed_bytes += int(res.get("freed_bytes", 0))
		deleted_files += int(res.get("deleted_files", 0))
		skipped_files += int(res.get("skipped_files", 0))

	return {
		"freed_bytes": freed_bytes,
		"deleted_files": deleted_files,
		"skipped_files": skipped_files,
		"formatted_freed": format_bytes(freed_bytes),
	}


## Formats a raw byte count into human-friendly representation (e.g. "140.2 MB", "3.4 GB").
static func format_bytes(bytes: int) -> String:
	if bytes <= 0:
		return "0 B"
	const KB := 1024.0
	const MB := 1024.0 * 1024.0
	const GB := 1024.0 * 1024.0 * 1024.0

	var f_bytes := float(bytes)
	if f_bytes >= GB:
		return "%.1f GB" % (f_bytes / GB)
	elif f_bytes >= MB:
		return "%.1f MB" % (f_bytes / MB)
	elif f_bytes >= KB:
		return "%.1f KB" % (f_bytes / KB)
	else:
		return "%d B" % bytes


#region Internal Recursive Helpers

static func _measure_dir_recursive(dir_path: String) -> Dictionary:
	var bytes: int = 0
	var files: int = 0
	var dir := DirAccess.open(dir_path)
	if not dir:
		return {"bytes": 0, "files": 0}

	dir.list_dir_begin()
	var name := dir.get_next()
	while not name.is_empty():
		if name != "." and name != "..":
			var full_path := dir_path.path_join(name)
			if dir.current_is_dir():
				var sub := _measure_dir_recursive(full_path)
				bytes += int(sub.get("bytes", 0))
				files += int(sub.get("files", 0))
			else:
				var file := FileAccess.open(full_path, FileAccess.READ)
				if file:
					bytes += file.get_length()
					file.close()
				files += 1
		name = dir.get_next()
	dir.list_dir_end()

	return {"bytes": bytes, "files": files}


static func _delete_dir_contents_recursive(dir_path: String) -> Dictionary:
	var freed: int = 0
	var deleted: int = 0
	var skipped: int = 0

	var dir := DirAccess.open(dir_path)
	if not dir:
		return {"freed_bytes": 0, "deleted_files": 0, "skipped_files": 0}

	dir.list_dir_begin()
	var name := dir.get_next()
	var subdirs_to_remove: Array[String] = []

	while not name.is_empty():
		if name != "." and name != "..":
			var full_path := dir_path.path_join(name)
			if dir.current_is_dir():
				var sub := _delete_dir_contents_recursive(full_path)
				freed += int(sub.get("freed_bytes", 0))
				deleted += int(sub.get("deleted_files", 0))
				skipped += int(sub.get("skipped_files", 0))
				subdirs_to_remove.append(full_path)
			else:
				var file_size: int = 0
				var file := FileAccess.open(full_path, FileAccess.READ)
				if file:
					file_size = file.get_length()
					file.close()

				var err := DirAccess.remove_absolute(full_path)
				if err == OK:
					freed += file_size
					deleted += 1
				else:
					skipped += 1
		name = dir.get_next()
	dir.list_dir_end()

	for sub_path in subdirs_to_remove:
		DirAccess.remove_absolute(sub_path)

	return {
		"freed_bytes": freed,
		"deleted_files": deleted,
		"skipped_files": skipped,
	}

#endregion
